### ISSUE TITLE
2301.1 not working due to ckeditor4

### ISSUE THREAD

**Issue by Ahoi-IT** [coremedia-contributions/blueprint-svg-support#1]
Hello @sbuettne . 

I can see that you've updated the versions to 2301.1.0, but unfortunately this doesn't work when integrated into an actual 2301.1 (or 2301.2) workspace. 

Reason: you're still using ckeditor4, but since 2210, only ckeditor5 is supported by default. See https://documentation.coremedia.com/cmcc-11/artifacts/2301/release-notes-webhelp/content/CMS-19191-1.html 

Can you confirm that this 2301 update is not complete or provide me with any information on how to integrate this contribution into a 2301 workspace?

Best regards,
Alexander

**Comment by sbuettne** [comment]
Hi Alex, thanks for the feedback. I will check and get back to you.

**Comment by sbuettne** [comment]
Hi Alex,

I pushed some minor changes on the cmcc-11-2301 and main branch to also support CKEditor 5.
Since customers can still downgrade to CKEditor 4, I will keep the CKEditor 4 plugin for now.
Please let me know, if you still have trouble integrating the extension into your project workspace.

Best regards,
Sebastian

**Comment by Ahoi-IT** [comment]
Hello @sbuettne.

Thanks for replying. 

I tried to integrate it into our 2301.2 CM workspace, but it is still failing:
When I try to integrate your code, pnpm cannot resolve the module: 

```
ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @coremedia/studio-client.main.ckeditor4-components@2301.1.0

The latest release of @coremedia/studio-client.main.ckeditor4-components is "2210.1.0".

If you need the full list of all 14 published versions run "$ pnpm view @coremedia/studio-client.main.ckeditor4-components versions".
```

Just to be sure: Didi this branch compile on your machine?  

Downgrading just this one module to 2210.1.0 didn't work either, because 2210.1.0 and 2301.1.0 (or 2301.2.0 as in our case) come with totally different versions of other modules such as `studio-client.cap-base-models`:

```
│ Building: @coremedia-blueprint/studio-client.main.svg-studio-plugin
│ Error: Cannot handle multiple versions of package @coremedia/studio-client.cap-base-models!
│ The following package(s) utilize(s) version 2301.2.0 (C:\dev\lgt-coremedia\apps\studio-client\node_modules\.pnpm\@coremedia+studio-client.cap-base-models@2301.2.0\node_modules\@coremedia\studio-client.cap-base-models\package.json):
│ - @coremedia-blueprint/studio-client.main.svg-studio-plugin (C:\dev\lgt-coremedia\modules\extensions\svg-support\apps\studio-client\apps\main\svg-studio-plugin\package.json)
│ - @coremedia-blueprint/studio-client.svg-plugin (C:\dev\lgt-coremedia\modules\extensions\svg-support\apps\studio-client\shared\js\svg-plugin\package.json)
...
│ The following package utilizes version 2210.1.0 (C:\dev\lgt-coremedia\apps\studio-client\node_modules\.pnpm\@coremedia+studio-client.cap-base-models@2210.1.0\node_modules\@coremedia\studio-client.cap-base-models\package.json):
│ - @coremedia/studio-client.main.ckeditor4-components (C:\dev\lgt-coremedia\apps\studio-client\node_modules\.pnpm\@coremedia+studio-client.main.ckeditor4-components@2210.1.0\node_modules\@coremedia\studio-client.main.ckeditor4-components\package.json)
│ Please make sure that all packages utilize the same version.
│     at collectDependencies (C:\dev\lgt-coremedia\apps\studio-client\node_modules\.pnpm\@jangaroo+core@1.4.1\node_modules\@jangaroo\core\graph.js:107:13)
```
